### ISSUE TITLE
When searching for a season that has some episodes but not all it returns "Show is already on plex"

### ISSUE THREAD

**Issue by chris243** [tidusjar/PlexRequests.Net#475] opened 2016-08-19 08:00 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9

#### Operating System:
Windows 10

Pretty much tittle. 
Ex: Game of thrones season 01 has only episode 1 and 2 go to Request->Select Season->Season 01->
Request=Show is already on Plex

**Comment by tidusjar** [comment] 2016-08-24 16:11
I just realised, this is not a bug. There is a option in the Plex settings to enable Episode searching.

What this option does is it scans your whole plex library and gets all of the TV Episodes and stores them into the DB every 12 hours.

If this option isn't enabled then we can only lookup on if you have the Season in Plex, in this case, you do have the season (But not all episodes).

Now the reason why this option is not enabled by default as it's a resource intensive task and while running the UI can slow down a lot (Depending on the size of your Plex Library it's hard to say how long it will run for).

If you do not want to enabled this, they still can request the episodes using the "Select Episodes..." option

**Comment by captainnapalm** [comment] 2016-08-24 22:03
Where is this setting in Plex? I couldn't find it.

**Comment by tidusjar** [comment] 2016-09-08 10:33
From @chris243 

>just to sum it up again. For some reason instead of searching for whatever episodes are missing for a selected season( Request->Select Season-> Season X) it returns Show already on plex when you have some but not all episodes. If you do the same to a season that has none of the episodes already downloaded, It goes and tells sonarr to download them just like it should. Basically having any episodes at all for a certain season makes plexrequests think you have the whole season and doesn't let you request it. I enabled Episode Searching in the settings and after 24hours it still didnt fix it for me.

**Comment by tidusjar** [comment] 2016-09-23 16:14
@chris243 Is this still an issue with the latest version?

**Comment by chris243** [comment] 2016-09-23 16:16
I will test it in a bit. I'll let you know.

**Comment by tidusjar** [comment] 2016-09-23 16:17
OK thanks!

**Comment by chris243** [comment] 2016-09-23 16:55
Just tested with newest stable release. Now when I search for a season with only some episodes it gives me the green message saying it requested but looking at sonarr logs it doesn't do anything. I tried searching for a season that I do have all episodes already and got same thing. Searching for a season with no episodes at all works as intended and sonarr searches for all episodes in that season.

**Comment by tidusjar** [comment] 2016-09-23 18:49
did you need to re-approve the request?

**Comment by tidusjar** [comment] 2016-10-07 22:11
@chris243 you have episode searching enabled right?

**Comment by chris243** [comment] 2016-10-07 22:13
Yes sir



Sent from my Sprint Samsung Galaxy® Note 4.


-------- Original message --------

**Comment by whitecollar17** [comment] 2016-10-27 16:06
fixed in the release of 1.9.5

**Closed by whitecollar17** 2016-10-27 16:06 UTC
Labels: Fixed in the next release
