### ISSUE TITLE
Bug: Sonarr Requests automatically set to unmonitored

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/PlexRequests.Net#496] opened 2016-08-23 19:43 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
win10

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1. Request all season/episodes of a  show
2. Approve the show
3. Check sonarr, the new show was submitted with all episodes that have already come out marked as not  monitored. so they never download.

**Comment by tidusjar** [comment] 2016-08-23 19:45
Duplicate of #487

**Closed** 2016-08-23 19:46 UTC
