### ISSUE TITLE
Movie Search and Suggestions not working with CouchPotato enabled

### ISSUE THREAD

**Issue by Narkyzz** [tidusjar/PlexRequests.Net#350] opened 2016-06-22 04:33 UTC
**Plex Requests.Net Version: 1.8.1**

**Operating System: Debian 8.5**

**Mono Version: Mono JIT compiler version 4.4.0**

**Reproduction Steps:**

Tried a fresh install, new PlexRequests database as well.

**Searching for a movie works only when CouchPotato is disabled.
Applies to manually searching and Suggestions**

TV Show searching is working fine, even with Sonarr enabled.

When searching or using the suggestions, the loading animation rolls indefinitely and no results are shown.
Tried with and without CouchPotato SubDirectory, same issue happens.

![image](https://cloud.githubusercontent.com/assets/17441057/16254497/8142a93c-380e-11e6-9885-b0223b5e07e5.png)

**Working configuration:**
Just disable CouchPotato.

**Not working configuration:**
CouchPotato enabled.
Hostname: localhost
Port: 5050
SSL: No

The 'Test Connectivity' is successful.

**Comment by tidusjar** [comment] 2016-06-22 07:47
Is there anything in your browsers console? (F12)

**Comment by Narkyzz** [comment] 2016-06-22 14:35
Yes, here's the error with CouchPotato enabled:

![image](https://cloud.githubusercontent.com/assets/17441057/16270484/7213bc48-3864-11e6-9156-590395873d16.png)

Nothing pops up in the console when it's disabled.

**Comment by tidusjar** [comment] 2016-06-22 14:37
That url, can you click on the network tab and you should see that request in red, and click it and press response?

Like the below:
![image](https://cloud.githubusercontent.com/assets/6642220/16270731/395a8370-388f-11e6-9802-191bc5b6aca9.png)

**Comment by Narkyzz** [comment] 2016-06-22 14:45
This is the 'upcoming' response:

{"statusCode":500,"message":"Something went horribly, horribly wrong while servicing your request.","details":"Nancy.RequestExecutionException: Oh noes! ---\u003e System.NullReferenceException: Object reference not set to an instance of an object\n  at PlexRequests.Services.Jobs.CouchPotatoCacher+\u003c\u003ec.\u003cQueuedIds\u003eb__15_0 (PlexRequests.Api.Models.Movie.Movie x) \u003c0x418b7130 + 0x00016\u003e in \u003cfilename unknown\u003e:0 \n  at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () \u003c0x418b6f60 + 0x00126\u003e in \u003cfilename unknown\u003e:0 \n  at System.Linq.Buffer`1[TElement]..ctor (IEnumerable`1 source) \u003c0x418b6b50 + 0x0023c\u003e in \u003cfilename unknown\u003e:0 \n  at System.Linq.Enumerable.ToArray[TSource] (IEnumerable`1 source) \u003c0x418b6ad0 + 0x0002f\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.Services.Jobs.CouchPotatoCacher.QueuedIds () \u003c0x418b64b0 + 0x00143\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003cProcessMovies\u003ed__78.MoveNext () \u003c0x418abac0 + 0x00add\u003e in \u003cfilename unknown\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () \u003c0x7f3d26d9f2a0 + 0x00029\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d170 + 0x000a7\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d0f0 + 0x0006b\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d0a0 + 0x0003a\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () \u003c0x7f3d26d9d4a0 + 0x00017\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003cUpcomingMovies\u003ed__75.MoveNext () \u003c0x418bc8a0 + 0x0017e\u003e in \u003cfilename unknown\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () \u003c0x7f3d26d9f2a0 + 0x00029\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d170 + 0x000a7\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d0f0 + 0x0006b\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) \u003c0x7f3d26d9d0a0 + 0x0003a\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () \u003c0x7f3d26d9d4a0 + 0x00017\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003c\u003c-ctor\u003eb__0_5\u003ed.MoveNext () \u003c0x418bc320 + 0x00152\u003e in \u003cfilename unknown\u003e:0 \n  --- End of inner exception stack trace ---\n  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) \u003c0x418b8a60 + 0x002d7\u003e in \u003cfilename unknown\u003e:0 "}

Sorry for the formatting, it was just one line.

**Comment by unhappyelf** [comment] 2016-06-22 17:56
I also have that same issue
Here is my response as well

{"statusCode":500,"message":"Something went horribly, horribly wrong while servicing your request.","details":"Nancy.RequestExecutionException: Oh noes! ---\u003e System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PlexRequests.Services.Jobs.CouchPotatoCacher.\u003c\u003ec.\u003cQueuedIds\u003eb__15_0(Movie x) in C:\\projects\\requestplex\\PlexRequests.Services\\Jobs\\CouchPotatoCacher.cs:line 90\r\n   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at PlexRequests.Services.Jobs.CouchPotatoCacher.QueuedIds() in C:\\projects\\requestplex\\PlexRequests.Services\\Jobs\\CouchPotatoCacher.cs:line 90\r\n   at PlexRequests.UI.Modules.SearchModule.\u003cProcessMovies\u003ed__78.MoveNext() in C:\\projects\\requestplex\\PlexRequests.UI\\Modules\\SearchModule.cs:line 219\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at PlexRequests.UI.Modules.SearchModule.\u003cUpcomingMovies\u003ed__75.MoveNext() in C:\\projects\\requestplex\\PlexRequests.UI\\Modules\\SearchModule.cs:line 156\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at PlexRequests.UI.Modules.SearchModule.\u003c\u003c-ctor\u003eb__0_5\u003ed.MoveNext() in C:\\projects\\requestplex\\PlexRequests.UI\\Modules\\SearchModule.cs:line 107\r\n   --- End of inner exception stack trace ---\r\n   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)"}

**Comment by tidusjar** [comment] 2016-06-22 19:17
Can someone send me a screenshot of their CP settings page?

**Comment by tidusjar** [comment] 2016-06-22 19:24
Actually can one of you guys test my fix? I can't reproduce the issue so I am just trying to fix the exception. The build should be ready within the next 10 mins:

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.549/artifacts

**Comment by Narkyzz** [comment] 2016-06-22 19:37
Don't know why my systemd stop always times out like that: plexrequests.service stop-sigterm timed out. Killing.

It still doesn't work for me. Doesn't seem to leave anything in the logs either.

This is the 'upcoming' response:

{"statusCode":500,"message":"Something went horribly, horribly wrong while servicing your request.","details":"Nancy.RequestExecutionException: Oh noes! ---\u003e System.NullReferenceException: Object reference not set to an instance of an object\n  at System.Linq.Enumerable+\u003cCastIterator\u003ec__Iterator17`1[TResult].MoveNext () \u003c0x41d2b200 + 0x0017c\u003e in \u003cfilename unknown\u003e:0 \n  at System.Linq.Buffer`1[TElement]..ctor (IEnumerable`1 source) \u003c0x41d2adc0 + 0x0023c\u003e in \u003cfilename unknown\u003e:0 \n  at System.Linq.Enumerable.ToArray[TSource] (IEnumerable`1 source) \u003c0x41d2ad40 + 0x0002f\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.Services.Jobs.CouchPotatoCacher.QueuedIds () \u003c0x41d2a560 + 0x0014b\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003cProcessMovies\u003ed__78.MoveNext () \u003c0x41d1f860 + 0x00ad1\u003e in \u003cfilename unknown\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () \u003c0x7f14d4d9b2a0 + 0x00029\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) \u003c0x7f14d4d99170 + 0x000a7\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) \u003c0x7f14d4d990f0 + 0x0006b\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) \u003c0x7f14d4d990a0 + 0x0003a\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () \u003c0x7f14d4d994a0 + 0x00017\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003cUpcomingMovies\u003ed__75.MoveNext () \u003c0x41d1f190 + 0x0017e\u003e in \u003cfilename unknown\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () \u003c0x7f14d4d9b2a0 + 0x00029\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) \u003c0x7f14d4d99170 + 0x000a7\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) \u003c0x7f14d4d990f0 + 0x0006b\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) \u003c0x7f14d4d990a0 + 0x0003a\u003e in \u003cfilename unknown\u003e:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () \u003c0x7f14d4d994a0 + 0x00017\u003e in \u003cfilename unknown\u003e:0 \n  at PlexRequests.UI.Modules.SearchModule+\u003c\u003c-ctor\u003eb__0_5\u003ed.MoveNext () \u003c0x41d1ec10 + 0x00152\u003e in \u003cfilename unknown\u003e:0 \n  --- End of inner exception stack trace ---\n  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) \u003c0x41d2d650 + 0x002d7\u003e in \u003cfilename unknown\u003e:0 "}

**Comment by tidusjar** [comment] 2016-06-22 19:58
Hmmm... I'm not sure how that is still possible. I'm going to add some logging in for that area and see if I can narrow it down. Can you try out a build with extra logging? It will be in an hour or so.

**Comment by Narkyzz** [comment] 2016-06-22 20:08
Yeah no problem. I can access plexrequests/search/movie/upcoming only when CouchPotato is disabled as well. Otherwise it gives the 500 InternalServerError

**Comment by unhappyelf** [comment] 2016-06-22 20:19
Ok this is going to sound noobish, but if I just leave the SqlTables.sql file in my current install will that preserve my settings when I try your fix?

**Comment by tidusjar** [comment] 2016-06-22 20:27
All of your settings are stored in plexrequests.sqlite

**Comment by tidusjar** [comment] 2016-06-22 20:51
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.551/artifacts

We should have some logs now. It starts with:

`This is not an error, starting to get the CP Cached Id's`

Can you do the search and post the logs.

(Logging at level `Error`).

**Comment by Narkyzz** [comment] 2016-06-22 21:04
Alright, this is what I get:

![image](https://cloud.githubusercontent.com/assets/17441057/16283559/43b98c06-389b-11e6-84c3-e00b9df71974.png)

**Comment by tidusjar** [comment] 2016-06-22 21:10
You restart and then it's fine?

So it's enabled, you disable it and then it doesn't work?

**Comment by Narkyzz** [comment] 2016-06-22 21:12
CP enabled: Doesn't work.
Disabling CP (without restarting PlexRequests): Doesn't work.
Restart PlexRequests (CP disabled): Works.

This is what it reports when the search works:

![image](https://cloud.githubusercontent.com/assets/17441057/16283812/69d39840-389c-11e6-8d82-060bb3ee4bda.png)

**Comment by unhappyelf** [comment] 2016-06-22 21:18
Here is mine if its any different

![image](https://cloud.githubusercontent.com/assets/1484041/16284005/d60ca0fe-3894-11e6-9b4d-aef653622af5.png)

**Comment by tidusjar** [comment] 2016-06-22 21:22
OK, this should fix it. New build will be here once it completes: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.552/artifacts

**Comment by Narkyzz** [comment] 2016-06-22 21:31
Yup, that fixed it :+1:
Thanks a lot.

**Comment by unhappyelf** [comment] 2016-06-22 21:32
Yes me too, thanks!

**Comment by tidusjar** [comment] 2016-06-22 21:43
You guys may as well use that build until the next release :)

**Closed** 2016-06-29 13:17 UTC
Labels: waiting for release
