### ISSUE TITLE
Automatic updates not working 

### ISSUE THREAD

**Issue by yeyeoke** [tidusjar/PlexRequests.Net#247] opened 2016-05-25 11:14 UTC
#### Plex Requests.Net Version:
1.7.2

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):
Nothing in logs
```



#### Reproduction Steps:

Pressing the update now in status doesnt work aswell as pressing "There is a new update available! Click Here!", it says updating but nothing happens.

**Comment by tidusjar** [comment] 2016-05-25 11:15
Duplicate of #236

**Closed by tidusjar** 2016-05-25 11:15 UTC
Labels: duplicate
