### ISSUE TITLE
[BUG] Requesting TV Series with ALL only picks latest season

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/PlexRequests.Net#502] opened 2016-08-24 19:16 UTC
#### Reproduction Steps:

Request TV Show with ALL seasons
It only picks the latest in sonarr the new TV Show only have monitored on the latest.

Proof:
Plex Request [http://i.imgur.com/pgZj27K.png](url)
Sonarr [http://i.imgur.com/gl11mwg.png](url)
Sonarr [http://i.imgur.com/s0O0uid.png](url)

**Comment by tidusjar** [comment] 2016-08-24 19:17
Duplicate of #487

**Closed by tidusjar** 2016-08-24 19:17 UTC
