### ISSUE TITLE
[FEATURE] Custom notifications

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/PlexRequests.Net#557] opened 2016-09-27 11:03 UTC
#### Plex Requests.Net Version:
 1.9.2

Allow custom notifications using notification tags and and exclusion tags.

For example if a movie or tv show is available or denied:
`<u>{title}</u>` is {availability} on Plex.

Resolution: `<b>{video_resolution}</b>`
Link: `<movie>``<a href="{imdb_url}">IMBd</a>``</movie><tv>``<a href="{thetvdb_url}">TVDB</a>``</tv>` 
Plex link: `<a href="{plex_url}">IMBd</a>`

**Comment by tidusjar** [comment] 2016-10-05 12:09
Duplicate of #182

**Closed by tidusjar** 2016-10-05 12:09 UTC
