### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#79] opened 2016-03-23 21:20 UTC
Using FreeNAS FreeNAS-9.3-STABLE-201602031011
Updated to v1.4.1 and now everytime I try to launch I get the following error. It worked fine before updating and even worked once after updating.

Unhandled Exception:
System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string
  at RestSharp.SimpleJson.DeserializeObject (System.String json) <0x8079eb570 + 0x00070> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) <0x8079eb3e0 + 0x00041> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x8079eb250 + 0x0003d> in <filename unknown>:0
  at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x8079e9e60 + 0x001e9> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at PlexRequests.Api.ApiRequest.Execute[T] (IRestRequest request, System.Uri baseUri) <0x80795cd20 + 0x00172> in <filename unknown>:0
  at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId (Int32 theTvDbId) <0x80795c130 + 0x00185> in <filename unknown>:0
  at PlexRequests.Core.Setup.MigrateDb () <0x806eb8c60 + 0x00475> in <filename unknown>:0
  at PlexRequests.Core.Setup.SetupDb () <0x803fc2660 + 0x00101> in <filename unknown>:0
  at PlexRequests.UI.Program.Main (System.String[] args) <0x803fb0760 + 0x0013b> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string
  at RestSharp.SimpleJson.DeserializeObject (System.String json) <0x8079eb570 + 0x00070> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) <0x8079eb3e0 + 0x00041> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x8079eb250 + 0x0003d> in <filename unknown>:0
  at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x8079e9e60 + 0x001e9> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at PlexRequests.Api.ApiRequest.Execute[T] (IRestRequest request, System.Uri baseUri) <0x80795cd20 + 0x00172> in <filename unknown>:0
  at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId (Int32 theTvDbId) <0x80795c130 + 0x00185> in <filename unknown>:0
  at PlexRequests.Core.Setup.MigrateDb () <0x806eb8c60 + 0x00475> in <filename unknown>:0
  at PlexRequests.Core.Setup.SetupDb () <0x803fc2660 + 0x00101> in <filename unknown>:0
  at PlexRequests.UI.Program.Main (System.String[] args) <0x803fb0760 + 0x0013b> in <filename unknown>:0

**Comment by tidusjar** [comment] 2016-03-23 21:23
Looks like it has attempted to upgrade the database and lookup all your requests to convert them over to the new format but has failed. This was a 1 time migration.

Sorry about this but are you able to delete the file in your install directory `plexrequests.sqlite`.

The reason we had to migrate the DB was so that all the requests could be stored in a different format that would not require database changes anymore.

**Comment by tedrock** [comment] 2016-03-23 21:26
Removed file, issue remains. Unless the file is stored outside the install location.

**Comment by tidusjar** [comment] 2016-03-23 21:27
Did you restart PlexRequests?  Can you please send me your log file located in the install directory e.g. `2016 03 23.log`

**Comment by tedrock** [comment] 2016-03-23 21:35
It will not start so I cannot restart it. I restarted the jail it's located in though.

The log does not appear to show anything relevant.
http://pastebin.com/Q3LdTmWJ

I originally attempted to restart because I could not logger connect to the tool. This is the second time the issue has occurred since updating, the first time I just deleted the whole thing and reinstalled and reconfigured.
It will not start so I cannot restart it. I restarted the jail it's located in though.

The log does not appear to show anything relevant.
http://pastebin.com/Q3LdTmWJ

I originally attempted to restart because I could not logger connect to the tool. This is the second time the issue has occurred since updating, the first time I just deleted the whole thing and reinstalled and reconfigured.

**Comment by tidusjar** [comment] 2016-03-23 21:38
So when the application starts up your get the error from the first post?

Are you sure there are no recent log files as it logs the following before entering any code:
`Getting product version`

**Comment by tedrock** [comment] 2016-03-23 21:41
https://www.dropbox.com/s/8bnfo3axj6x67js/www.dropbox.com.url?dl=0 that's the log file there are two others, one for the 22nd and one for the 21st. I also just discovered I can run it fine via Windows by double clicking the EXE. That caused a new PlexRequests.sqlite to be created but I still cannot launch it via FreeNAS.

**Comment by tidusjar** [comment] 2016-03-23 21:49
Thats strange, the reason why there is nothing in the 2nd log is because it rolled over from the 21st.

1. So are you still getting the same error from the first post?
1. What mono version are you running?

**Comment by tedrock** [comment] 2016-03-23 21:55
Mono JIT compiler version 4.2.2 (Stable 4.2.2.10/7b87787 Sat Mar 12 03:34:34 UTC 2016)
I am getting the same error but I just noticed github converted some of it to formatting.

Here is the full error:
`Version: 1.4.1

Unhandled Exception:
System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string
  at RestSharp.SimpleJson.DeserializeObject (System.String json) <0x807de7570 + 0x00070> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) <0x807de73e0 + 0x00041> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x807de7250 + 0x0003d> in <filename unknown>:0
  at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x807de5e60 + 0x001e9> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at PlexRequests.Api.ApiRequest.Execute[T] (IRestRequest request, System.Uri baseUri) <0x807d5cd20 + 0x00172> in <filename unknown>:0
  at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId (Int32 theTvDbId) <0x807d5c130 + 0x00185> in <filename unknown>:0
  at PlexRequests.Core.Setup.MigrateDb () <0x806eb8c60 + 0x00475> in <filename unknown>:0
  at PlexRequests.Core.Setup.SetupDb () <0x803fc5de0 + 0x00101> in <filename unknown>:0
  at PlexRequests.UI.Program.Main (System.String[] args) <0x803fb0760 + 0x0013b> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string
  at RestSharp.SimpleJson.DeserializeObject (System.String json) <0x807de7570 + 0x00070> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) <0x807de73e0 + 0x00041> in <filename unknown>:0
  at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x807de7250 + 0x0003d> in <filename unknown>:0
  at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x807de5e60 + 0x001e9> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at PlexRequests.Api.ApiRequest.Execute[T] (IRestRequest request, System.Uri baseUri) <0x807d5cd20 + 0x00172> in <filename unknown>:0
  at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId (Int32 theTvDbId) <0x807d5c130 + 0x00185> in <filename unknown>:0
  at PlexRequests.Core.Setup.MigrateDb () <0x806eb8c60 + 0x00475> in <filename unknown>:0
  at PlexRequests.Core.Setup.SetupDb () <0x803fc5de0 + 0x00101> in <filename unknown>:0
  at PlexRequests.UI.Program.Main (System.String[] args) <0x803fb0760 + 0x0013b> in <filename unknown>:0
`

**Comment by tidusjar** [comment] 2016-03-23 22:01
That's fine, I know what is going on but I don't understand how. 

If you have deleted your database it should not go to this line in the log `PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId`

This bit of code will stop it https://github.com/tidusjar/PlexRequests.Net/blob/master/PlexRequests.Core/Setup.cs#l90

Are you able to send me your database? the `plexrequests.sqlite` that is in the install folder?

**Comment by tedrock** [comment] 2016-03-23 22:04
Do you have an email or anything I can send it to? One of the databases I'm going to surely has API keys and other information I'd rather not make public.

**Comment by tedrock** [comment] 2016-03-23 22:10
Wow... I got it to run. I was running it like this before:
`mono /InstallLocation/Plex\ Requests/PlexRequests.exe`
But I tried going into the install folder and running it and it ran fine. I ran it successfully this way multiple times before updating and even a few times after updating.

**Comment by tidusjar** [comment] 2016-03-23 22:12
You can send it to jamierees@outlook.com  all of the information is encrypted so it would be difficult to find out unless someone started reverse engineering the code. 

That is very strange. I'll take a look to see if I can reproduce this.

**Comment by tedrock** [comment] 2016-03-23 22:14
I doubt you want the databases anymore?

**Comment by tidusjar** [comment] 2016-03-23 22:17
Yeah probably not. I'll take a look at this tomorrow.

**Comment by tidusjar** [comment] 2016-03-24 09:30
@tedrock Ah, it's because the database you was deleting was not being created in the install directory, it was being created where you was running the terminal command. I'll take a look at fixing this at some point.

**Comment by tedrock** [comment] 2016-03-24 15:41
I kind of suspected this, it would explain why my settings were erased and why it worked once or twice depending on how where I was typing the command.

**Comment by tidusjar** [comment] 2016-03-24 15:44
Yep, I know why this is happening. Just need to work out how to correctly locate the directory for each platform.

**Comment by tidusjar** [comment] 2016-04-04 11:24
This has been fixed in V1.6

**Closed by tidusjar** 2016-04-04 11:24 UTC
Labels: enhancement
