### ISSUE TITLE
Plex theme for mobile

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/PlexRequests.Net#271] opened 2016-05-26 11:43 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.4

#### Operating System:
Docker

#### Reproduction Steps:
Open the request page with plex theme, and the blue theme, then you will see a difference. Screenshots below.
![screenshot_20160526-130842](https://cloud.githubusercontent.com/assets/4106070/15573505/cfb4a290-2347-11e6-8d71-5c11b099a42f.png)
![screenshot_20160526-130857](https://cloud.githubusercontent.com/assets/4106070/15573506/d3b95d2c-2347-11e6-9667-ba71e3a5bbc1.png)

**Comment by tidusjar** [comment] 2016-05-26 12:00
This is a duplicate of #256 . I'm going to close this since #256 is the master issue. But this is a good example of what needs to be changed.

**Closed by tidusjar** 2016-05-26 12:00 UTC
Labels: duplicate
