### ISSUE TITLE
JSON errors when using Approve All

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#85] opened 2016-03-25 00:46 UTC
Tried to use Approve All for _lots_ of movies and a few TV shows. Clicking on Approve All gives the Something Went Wrong error.

Looking at the error, it states:
`2016/03/24 19:37:10.781 PlexRequests.Api.ApiRequest Fatal: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 101
2016/03/24 19:37:10.781 PlexRequests.Api.ApiRequest Info: [
  {
    "propertyName": "TvdbId",
    "errorMessage": "This series has already been added",
    "attemptedValue": 71889,
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Tvdb Id",
      "propertyValue": 71889
    }
  }
]
`

That TV Show that it's referencing is Boy Meets World. Had a user request this Show a while back, I went and manually got matching files, but never Approved it in Plex Requests.

So it appears that there's a bug where if a Show (maybe even movie) is requested, it checks Plex, see's it's missing and adds to Requests, then if it is added to Plex before the show is Approved in Requests, it fails.

**Comment by Auwen** [comment] 2016-03-25 00:59
I was able to Delete the shows that I had manually added, re-ran Approve All and it worked.

**Comment by shiitake** [comment] 2016-03-25 03:01
@Auwen - you're correct in your assessment. PR checks Plex when the request is created but it probably needs to check Plex again if approval is required for the requests. 

At least there is a workaround for it.

**Comment by tidusjar** [comment] 2016-03-25 13:19
I think the issue is thatwe are attempting to try and add it to Sonarr/SickRage but it is already present.

    "errorMessage": "This series has already been added"

 We could check if it's in Plex when approving but it might not be in Plex but will be in Sonarr/SickRage...

I might be worth Rechecking if the content is in Plex and also see if we are able to check the `errorMessage` we get back.

**Comment by tidusjar** [comment] 2016-03-29 09:49
The code has been changed to now feedback any errors we get from Sonarr back to the user. So if the series is already in Plex the user will be notified in the UI for this. In regards to 'approve all', We log that the series is in Plex so we couldn't send it over rather than an error message

**Closed** 2016-03-29 09:49 UTC
Labels: bug
