### ISSUE TITLE
New user management system is unstable

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#690] opened 2016-11-17 21:13 UTC
End users got errors that they have not the right permission for request a movie.
But plex request add the show to the failed queue. 

(end user has the right permission)

If i try it on my self, i got the error to.  If i go to the user mangement page, i got this page:

![image](https://cloud.githubusercontent.com/assets/2944704/20407520/081502d4-ad12-11e6-895e-da867f719957.png)

after a f5 the page is working,  but request something isn't possible

**Comment by tidusjar** [comment] 2016-11-18 08:51
You sure that the user didn't have the 'Read Only' Permission?
That permission means that they cannot do anything on the system other than view

**Comment by tidusjar** [comment] 2016-11-18 09:07
I also cannot reproduce the error you see above 😢

**Comment by SuperPotatoMen** [comment] 2016-11-18 11:41
![image](https://cloud.githubusercontent.com/assets/2944704/20428990/5c87d902-ad8c-11e6-97e0-333eba163c8e.png)

**Comment by tidusjar** [comment] 2016-11-18 11:43
AH it's a Plex User. I'll take another look

**Comment by SuperPotatoMen** [comment] 2016-11-18 11:54
Whoops, i didn't say that, i'm sorry :(

**Comment by tidusjar** [comment] 2016-11-20 19:22
This should now be fixed in the latest dev. You just need to delete the Plex Users table!

**Comment by tidusjar** [comment] 2016-11-20 19:23
Or delete the migration row again

**Closed by tidusjar** 2016-11-20 19:22 UTC
Labels: bug, Dev/beta version, in progress, Priority High
