### ISSUE TITLE
Modify recently added email

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#602] opened 2016-10-19 19:45 UTC
Can you modify or possibly create an option to bcc everyone that recieves the recently added content? I have around 50 users and it would be awesome if everyone that received the email wasn't able to see everyone else's email addresses in the "To:" field. Thanks.

**Comment by tidusjar** [comment] 2016-10-19 19:46
It does BCC everyone. Are you not seeing that behaviour?

**Comment by chrisausbun** [comment] 2016-10-19 20:10
Hi Jamie,


Thank you for the quick response, I greatly appreciate it. Unfortunately, no I'm not seeing that behavior. I've attached a couple screenshots I took with my iPhone. This email is being sent to an extra plex account I created (not my main admin account) that is being sent to my Gmail account instead of my Hotmail which is what I use to send the recently added email out.


________________________________

**Comment by tidusjar** [comment] 2016-10-19 20:17
@chrisausbun There are no attachments, I don't think github supports email attachments

**Comment by chrisausbun** [comment] 2016-10-19 20:23
No worries, I'll insert the screenshots inside the email.


[cid:4ad10e62-c68a-4b9a-803a-ad115874af92][cid:0ec5cd6f-5b64-4cd2-8360-70cdcb7bf295]


________________________________

**Comment by chrisausbun** [comment] 2016-10-19 20:25
Here you go. 
![img_0122](https://cloud.githubusercontent.com/assets/22944072/19536107/68405e44-95ff-11e6-9fdc-a9f6f745cb50.PNG)
![img_0123](https://cloud.githubusercontent.com/assets/22944072/19536111/6d0a4a98-95ff-11e6-81c5-90c260063756.PNG)

**Comment by chrisausbun** [comment] 2016-10-19 20:33
Hopefully this works!
![img_0122](https://cloud.githubusercontent.com/assets/22944072/19536382/9b028798-9600-11e6-8098-d2c5d6d730df.PNG)

**Comment by tidusjar** [comment] 2016-10-19 20:49
Just looked into this,

I'm pretty sure you can only see the TO recipients since it's sent from your mail.

I just tested on a bunch of users and they cannot see the recipients.

**Comment by chrisausbun** [comment] 2016-10-19 21:37
I actually have 2 different mail accounts, the hotmail is the one who's sending it to everyone but my gmail is just a recipient. Plus I also checked another one of my users and they can see everyone else who it was sent to as well.

**Comment by chrisausbun** [comment] 2016-10-19 21:39
I was also having the issue when I upgraded to 1.9.4 where the email wouldn't send and the test came back with a null error so I used the 1.9.3 version you listed in your thread regarding this issue. Not too sure if it's just a problem with that 1.9.3 version you created or not. Thanks for looking into this.

**Comment by tidusjar** [comment] 2016-10-19 21:50
Strange, can you try a dev build to make sure the issue is still present?

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.865/artifacts

**Comment by chrisausbun** [comment] 2016-10-19 22:26
I went ahead and tried the dev build. However, it won't send to all users. I tried the send test to admin and that worked but when I unchecked the option to send to everyone, hit submit, then re-checked send all users, and hit submit, it didn't send.

**Comment by tidusjar** [comment] 2016-10-19 22:35
It sends on a schedule, check the Schedule Settings page.

**Comment by chrisausbun** [comment] 2016-10-20 00:16
When I go to Scheduled Jobs, this is what I get 
![scheduled jobs error](https://cloud.githubusercontent.com/assets/22944072/19542001/bf4a9ff4-961f-11e6-9628-b1316b400a14.png)

**Comment by chrisausbun** [comment] 2016-10-24 00:06
I reverted back to 1.9.3 and I don't see Schedule settings anywhere. All I see is the scheduled jobs page which only has Recently Added Email (hours). Is that what you were talking about for schedule settings?

**Comment by tidusjar** [comment] 2016-10-24 07:57
Sorry @chrisausbun Yes that is what I was on about. I've fixed the error above. 
Here is the latest version: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.875/artifacts

**Comment by chrisausbun** [comment] 2016-10-24 13:34
Just opened up newsletter settings, and this is what I got: 

Error Details

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'NewsletterSettings'
Currently available view engine extensions: sshtml,html,htm,cshtml,vbhtml
Locations inspected: views/admin/Admin/NewsletterSettings-en-US,views/admin/Admin/NewsletterSettings,admin/Admin/NewsletterSettings-en-US,admin/Admin/NewsletterSettings,views/admin/NewsletterSettings-en-US,views/admin/NewsletterSettings,admin/NewsletterSettings-en-US,admin/NewsletterSettings,views/Admin/NewsletterSettings-en-US,views/Admin/NewsletterSettings,Admin/NewsletterSettings-en-US,Admin/NewsletterSettings,views/NewsletterSettings-en-US,views/NewsletterSettings,NewsletterSettings-en-US,NewsletterSettings
Root path: C:\PlexRequests.net
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , DefaultViewFactory , Object , Object , ViewLocationContext )
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IViewFactory , String , Object , ViewLocationContext )
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IResponseProcessor , String , Object , NancyContext )
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , IResponseNegotiator , Object , NancyContext )
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by tidusjar** [comment] 2016-10-25 14:52
Sorry can you try now: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by tidusjar** [comment] 2016-10-25 19:01
Did you unblock the zip?

**Comment by tidusjar** [comment] 2016-10-28 10:53
Has this been resolved in the latest version?

**Comment by SuperPotatoMen** [comment] 2016-11-02 21:48
Closed, no answer after 8 days :(

**Closed by SuperPotatoMen** 2016-11-02 21:48 UTC
Labels: Waiting on feedback
