### ISSUE TITLE
No PushBullet Notifications  / Log Level not saved?

### ISSUE THREAD

**Issue by AmansRevenger** [tidusjar/PlexRequests.Net#141] opened 2016-04-06 11:26 UTC
I cant get any PushBullet Notifications working, I can even put in an empty PushBullet API key and it will say "Successfully sent a test Pushbullet Notification!". But also nothing will show up in the logs, since I am stuck on Trace Level, I can change it and get a "The new log level is now Debug" message, but it will be Trace again upon reloading / revisiting the log settings.

I already checked the permissions on /var/lib/PlexRequest/prq_net/ and they are ok. I also have everything else working just fine (requesting, connection to Sonarr, PMS and CouchPotato, availability checker etc) it's "just" the Notifications and Logs not working.

#### Operating System: 

Linux 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### Mono Version:

Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by tidusjar** [comment] 2016-04-06 11:40
Can you show the logs in the `logs` folder in the install directory?

**Comment by AmansRevenger** [comment] 2016-04-06 11:44
I honestly dont know how to mask the information in the logs...

**Comment by tidusjar** [comment] 2016-04-06 11:47
Could you delete the file, send off a test message and then email the file to jamierees@outlook.com ?

That way there is very little information in there?
(The application will recreate the log file).

**Comment by AmansRevenger** [comment] 2016-04-06 12:00
Here are the logs with most of it redacted, but I restarted PlexRequest and now it wont create a new log file ... what the hell

[2016-04-02.txt](https://github.com/tidusjar/PlexRequests.Net/files/206334/2016-04-02.txt)
[2016-04-06.txt](https://github.com/tidusjar/PlexRequests.Net/files/206335/2016-04-06.txt)
[2016-04-03.txt](https://github.com/tidusjar/PlexRequests.Net/files/206337/2016-04-03.txt)
[2016-04-05.txt](https://github.com/tidusjar/PlexRequests.Net/files/206336/2016-04-05.txt)

**Comment by tidusjar** [comment] 2016-04-06 12:04
It will create a new log file on the first instance it logs something. If it's not logging anything then a new file will not be created. Thanks I will take a look through.

**Comment by tidusjar** [comment] 2016-04-06 12:18
Any idea @Drewster727 ?

**Comment by AmansRevenger** [comment] 2016-04-06 12:23
I randomly got a Test Notification just now

![image](https://cloud.githubusercontent.com/assets/18306225/14316394/f8e5aa04-fc02-11e5-8eeb-d7edcb0bc851.png)

Weird thing is ... I wasnt even testing it right now.

**Comment by tidusjar** [comment] 2016-04-06 12:30
Are you 100% you replaced all of the files? Can you just install the application to a different directory and copy the `plexrequests.sqlite` file over? 

It sounds like you are missing something.

**Comment by AmansRevenger** [comment] 2016-04-06 13:13
New Install + old sqlite = same issue, no Logs folder gets created, nothing get's logged outside of the UI, log setting reverts to trace (or never get's changed at all, which is more likely).

i will try around a bit more and report back!

**Comment by AmansRevenger** [comment] 2016-04-06 13:21
Ok it doesnt log to the application path (/var/lib/PlexRequests/ for example) but to the log file folder of the user

/home/<username>/logs

and with a FRESH install and everything I get this logged:

2016/04/06 15:12:37.117 PlexRequests.UI.Program Info: We are going to use port 3001 that was passed in
2016/04/06 15:12:37.164 PlexRequests.UI.Program Trace: Getting product version
2016/04/06 15:12:37.173 PlexRequests.UI.Program Info: Version: 1.6.0
2016/04/06 15:12:37.337 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/04/06 15:12:48.072 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/04/06 15:12:48.081 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/04/06 15:13:39.195 PlexRequests.UI.Program Trace: We are on Mono! 
2016/04/06 15:14:45.202 PlexRequests.UI.Modules.SearchModule Trace: Loading Index 
2016/04/06 15:14:56.267 PlexRequests.UI.Modules.AdminModule Trace: Getting Settings: 
2016/04/06 15:14:56.285 PlexRequests.UI.Modules.AdminModule Trace: {
  "Port": 0,
  "SearchForMovies": true,
  "SearchForTvShows": true,
  "SearchForMusic": false,
  "RequireMovieApproval": true,
  "RequireTvShowApproval": true,
  "RequireMusicApproval": false,
  "UsersCanViewOnlyOwnRequests": false,
  "WeeklyRequestLimit": 0,
  "NoApprovalUsers": null,
  "Id": 0
} 
2016/04/06 15:15:15.178 PlexRequests.UI.Modules.AdminModule Trace: {
  "Enabled": true,
  "AccessToken": "MY ACCESS TOKEN",
  "DeviceIdentifier": null,
  "Id": 0
} 
2016/04/06 15:15:15.519 PlexRequests.UI.Modules.AdminModule Info: Saved email settings, result: True 
2016/04/06 15:15:17.288 PlexRequests.UI.Modules.AdminModule Info: Sent pushbullet notification test 


And I never get a notification.

**Comment by AmansRevenger** [comment] 2016-04-06 14:05
What I got so far:

As long as I dont try to change the Log Setting (Trace, Debug etc), it logs happily into the home directory.

As soon as I submit something on the Log UI, it stops logging anywhere as far as I can tell.

Also despite the settings being correctly shown (as proven above in the log) for Pushbullet and Email, AND saying it sent a test notification, it wont work.

Currently in the process of apt-get update and upgrading everything and then reporting back.

**Comment by tidusjar** [comment] 2016-04-06 14:12
I think it's logging to the home directory because that's the current directory your user is in when running the command to launch PlexRequests? That's a bug.

**Comment by tidusjar** [comment] 2016-04-06 14:17
@AmansRevenger On the server you are running PlexRequests on, can you navigate to this? https://YourAPIKey@api.pushbullet.com/v2/pushes

It should display a bunch of your pushes to yourself. I just want to make sure your sever can communicate with pushbullets endpoint.

**Comment by AmansRevenger** [comment] 2016-04-06 15:06
I have PlexPy Running on the same server and get those notifications without problems. So yes, it can communicate on that API Key.

and I ALSO have ONE (the one mentioned above) message from Plex Request

`{"active":true,"iden":"ujy3J8b6PAqsjAzl8opNa8","created":1.4599452690832582e+09,"modified":1.4599453282422552e+09,"type":"note","dismissed":true,"direction":"self","sender_iden":"ujy3J8b6PAq","sender_email":"REDACTED","sender_email_normalized":"REDACTED","sender_name":"Aman Iman","receiver_iden":"ujy3J8b6PAq","receiver_email":"aman1992@live.de","receiver_email_normalized":"aman1992@live.de","awake_app_guids":["web-kn3kf4g29eg6ivu9b621g8"],"title":"Plex Requests: Test Message!","body":"This is just a test! Success!"},`

so ... it worked once and not anymore. 


I run PlexRequests with

`sudo screen sudo mono /path/to/plex/requests.exe `

so I should run it as root... but the logs are in the home directory of the only user I ever created (netbook)...

**Comment by tidusjar** [comment] 2016-04-07 07:51
This has really confused me, It doesn't make much sense.

**Comment by csy7550** [comment] 2016-04-07 20:23
I can confirm that change of the log level does not work. The logging of the plex availability checker has made my log grow to 500MB in 7 hours.

**Comment by tidusjar** [comment] 2016-04-07 20:29
@csy7550 ok thanks for letting me know. I'll fix that and reduce the logging.

**Comment by tidusjar** [comment] 2016-04-07 21:23
@csy7550 Regarding the log level, the file log is set at Trace by default (Most verbose logs). If you change the log level in the UI to `Info` (Best user friendly information) it should fix it. I have tested out the logging and it seems to be working as expected.

**Comment by csy7550** [comment] 2016-04-08 06:00
I've changed it to info now, let's see :) Had it set to error. The reason I thought the log level won't save is because the dropdown menu always says "Trace" when you reload the page after you submit the changes.

**Comment by tidusjar** [comment] 2016-04-08 06:02
The dropdown menu doesn't reflect the current log level.

**Comment by csy7550** [comment] 2016-04-08 13:27
Changed to "info", but still log is 700MB for today and to big to open, but the old one was full of plex availability checking so I'm guessing that's whats in there.

**Comment by tidusjar** [comment] 2016-04-08 13:29
@csy7550 Do you have Plex configured in Plex Requests? The Plex IP and the Auth token under Authentication?

**Comment by csy7550** [comment] 2016-04-08 13:36
Yes, everything set up and working. I've noticed availability changes almost instantaneous after a request is available so maybe the frequency can be changed a bit? I've deleted the logs now and restarted plexrequest, I'll zip and attach a log when I get home/have time.

**Comment by tidusjar** [comment] 2016-04-08 13:54
@csy7550 I have also noticed from viewing a few peoples logs that the plex checker is checking more than the frequency set. So I need to look into that.

**Comment by csy7550** [comment] 2016-04-08 16:48
Where can I send the logs? I don't want to go through 10000 lines and remove sensitive information so I would like to send you in private

**Comment by tidusjar** [comment] 2016-04-08 18:43
jamierees@outlook.com

**Comment by tidusjar** [comment] 2016-04-16 13:52
Fixed in release 1.6.1

**Closed by tidusjar** 2016-04-16 13:52 UTC
Labels: bug
