### ISSUE TITLE
Plex Requests querying Plex incorrectly?

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#108] opened 2016-03-27 15:18 UTC
There are a few movies that Plex Requests seems to get confused when querying Plex. If I try to add Joy to PR, it says that I already have it but I don't. I have several episodes of different with the word "joy" in them and a show, "The Joy of Painting".

It also says that I have The Jungle Book (2016) but that's not even out yet, though I do have the 1967 version.

But what seems odd is that there's no rhyme or reason as far as I can tell. It's not like it gets confused if there's a single word movie matching another movie's title, as I tried requesting Alien when I had Alien vs Predator, etc.

**Comment by tidusjar** [comment] 2016-03-27 19:49
Yeah that's slightly a problem.

I think this area needs to be taken a look at, at first it would try and match the title, but sometimes the title contains a year or is slightly different than what TheTVDB contains, so I included the year of the movie too...

But we are doing a `contains` so this is a bug. I suggest we fix this asap.

**Comment by tidusjar** [comment] 2016-03-29 07:47
The issue is that if we do an exact match on the Title I am worried that the titles will differ in Plex compared to TVMaze, we need to match on Title and Year as Plex does not provide any sort of unique id in it's API's.

**Comment by tidusjar** [comment] 2016-03-29 09:38
@Auwen How much is this bug preventing you from working with PlexRequests?

I am debating to either wait until the next release or push out a minor build (v1.5.3).

**Comment by Auwen** [comment] 2016-03-29 11:48
It's annoying, but not workflow breaking as I can always add manually to CouchPotato. No user has ran into the issue yet to my knowledge.

**Comment by tidusjar** [comment] 2016-03-29 11:49
Well the next release will possibly be next week sometime. So it might be worth me pushing out a minor release.

**Comment by Auwen** [comment] 2016-03-29 11:53
Next week is well soon enough for me. Most of my large requests are done and I'm patient.

**Comment by tidusjar** [comment] 2016-03-29 11:54
Ok no problem, I will close of this issue since it has been fixed in the code and will be in the next release (Date TBC but sometime next week hopefully).

**Closed by tidusjar** 2016-03-29 11:54 UTC
Labels: bug
