### ISSUE TITLE
Show before the login button not working

### ISSUE THREAD

**Issue by justinglock40** [tidusjar/PlexRequests.Net#703] opened 2016-11-24 22:31 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Fedorea 23

#### Mono Version:
4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

Logs doesn't show that anything changed when clicking the radio button to enable the landing page prior to user log-in.

**Comment by SuperPotatoMen** [comment] 2016-11-25 00:57
I'm not sure what the problem is right now?
You can turn the landing on before ore after te login page.
![image](https://cloud.githubusercontent.com/assets/2944704/20611868/769fe778-b2b2-11e6-9797-ab2e1b845cd7.png)

**Comment by justinglock40** [comment] 2016-11-25 01:05
Yea you can based on what's there but in actuality it only shows up if you set it to show up after login

**Comment by SuperPotatoMen** [comment] 2016-11-25 01:22
I understand the problem now. I can reproduce the problem to.
If i use the button "Show before the login" it didn't popup before te login, just after.

**Comment by justinglock40** [comment] 2016-11-25 01:24
Exactly

**Comment by SuperPotatoMen** [comment] 2016-11-25 01:33
Not sure if we can make a fix in the upcomin release of 1.10.0 but it will be definitely fixed in the 1.10.0.

Planned now for 1.10.0 release

**Comment by justinglock40** [comment] 2016-11-25 01:35
Thanks!

**Closed** 2016-11-25 08:40 UTC
Labels: bug, Fixed in the next release, Priority Low

**Comment by SuperPotatoMen** [comment] 2016-11-25 17:04
Fixed in the next release!

**Comment by SuperPotatoMen** [comment] 2016-11-25 23:38
Tested the fix in dev branch,fix confirmed

**Comment by justinglock40** [comment] 2016-11-25 23:39
Cool thanks
