### ISSUE TITLE
database file has ballooned to 30GB. 

### ISSUE THREAD

**Issue by sch1308** [tidusjar/PlexRequests.Net#325] opened 2016-06-17 04:31 UTC
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Operating System:

Win 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```


Logs go here (Please make sure you remove any personal information from the logs)
```

![image](https://cloud.githubusercontent.com/assets/7896067/16140793/6c134372-3422-11e6-8966-0a7c421682f5.png)

![image](https://cloud.githubusercontent.com/assets/7896067/16140803/7e32622c-3422-11e6-9d75-88f2b2732371.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment] 2016-06-17 07:35
Damn, yes so I know what the problem is and it has been fixed in the dev build.

This is due to your log level being set to `Trace`. The best thing you can do is delete the backups and delete the sqlite file. Or you can wait for the next release and we should automatically clean your database for you.

**Closed** 2016-06-21 07:43 UTC
